### ISSUE TITLE
RE: IndexOutOfRangeException in LinqJoinKeyHelper.CreateKeySelectors

### ISSUE THREAD

**Issue by RobLSDev** [zzzprojects/nmemory#2]
I hate to cross post from the codeplex site, but it looks like they are still having issues over there with new posts.  This is in response to https://nmemory.codeplex.com/workitem/4

I believe that I may also be working on a project that is having this same issue.  Below is the truncated stack.  I'm going to try and isolate the issue into a test project so you can repo it.

```
Test Name:  GetUser_ValidGuid_ReturnsUser
Test FullName:  Business.Tests.UserMgrTests.GetUser_ValidGuid_ReturnsUser
Test Source:    l:\vs projects\Tests\Business\UserMgrTests.cs : line 18
Test Outcome:   Failed
Test Duration:  0:00:11.5376442

Result Message: 
Test method Business.Tests.UserMgrTests.GetUser_ValidGuid_ReturnsUser threw exception: 
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
Result StackTrace:  
at NMemory.Common.LinqJoinKeyHelper.CreateKeySelectors(Type outerType, Type innerType, IExpressionBuilder[] outerKeyCreator, IExpressionBuilder[] innerKeyCreator, LambdaExpression& outerKey, LambdaExpression& innerKey)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.Optimization.Rewriters.InnerJoinLogicalRewriter.VisitMethodCall(MethodCallExpression node)
   at NMemory.Execution.QueryCompilerBase.TransformExpression(Expression expression, ITransformationContext context, TransformationStepRecorder recorder)
   at NMemory.Execution.QueryCompilerBase.Compile[T](Expression expression)
   at NMemory.Linq.TableQuery`1.GetEnumerator(IDictionary`2 parameters, Transaction transaction)
   at NMemory.Linq.TableQueryWrapper`1.System.Collections.IEnumerable.GetEnumerator()
   at Effort.Provider.EffortDataReader..ctor(IEnumerable result, Int32 recordsAffected, FieldDescription[] fields, DbContainer container)
   at Effort.Internal.CommandActions.QueryCommandAction.ExecuteDataReader(ActionContext context)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
 --- End of inner exception stack trace ---
    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
[Truncated Internal Code Stack]
```

**Comment by RobLSDev** [comment]
So I was able to put some code together that demonstrates the issue.  _AND_ I was able to attach it to the original CodePlex issue.  Please check out EffortTest.zip and let me know if you have any questions.

**Comment by ditmermda** [comment]
@RobLSDev How come you closed this issue? I see other issues very similar (same method throwing that exception).

Did you find a fix?

Related open issues:
- https://github.com/tamasflamich/nmemory/issues/4
- http://effort.codeplex.com/workitem/755

**Comment by RobLSDev** [comment]
Unfortunately I never did get a fix.  Back when I posted this it looked like the maintainer was primarily using codeplex, and not github for bug tracking.  However, codeplex was having some problems so I tried cross-posting here in an effort to get some repro info submitted.  I closed this issue once I was able to successfully post in codeplex again.  https://nmemory.codeplex.com/workitem/4

**Comment by ditmermda** [comment]
@RobLSDev I see, I had of course hoped you had found a solution in the meantime. 

It is strange why the developer has chosen to create a github mirror, and not instead just simply transferred everything over to GitHub and closed the CodePlex page - even Microsoft have moved much development into GitHub (Roslyn for example).
