### ISSUE TITLE
Error code: GenericError after insert 10M rows

### ISSUE THREAD

**Issue by ednsinf** [zzzprojects/nmemory#56]
Error code: GenericError after insert 10M rows in loop for

   at NMemory.Tables.Table`2.Insert(TEntity entity, Transaction transaction)
   at NMemory.Tables.Table`2.Insert(TEntity entity)
   
Recomendation to fix: use buferred stream and flush in database stream

**Comment by JonathanMagnan** [comment]
Hello @ednsinf ,

We didn't get any error even after inserting 20M rows:

```csharp
MyDatabase myDatabase = new MyDatabase();

for(int i = 0; i < 20000000; i++)
{
	myDatabase.Tests.Insert(new Test() { Id = i, Term1 = "z_1", Term2 = "z_2" });
}
```

Please ensure to include a project like we ask when you create a new issue.

Depending on what you are looking for, they might have a better alternative than nmemory such as [SQLite InMemory](https://www.sqlite.org/draft/inmemorydb.html).

Best Regards,

Jon
